Ref.DIR_DATA_Ref <- './Data/Ref/'
Ref.DIR_DATA_MEF <- './Data/MEF/'
Ref.DIR_DATA_Lit <- './Data/Lit/'
Ref.DIR_DATA_Pop <- './Data/Pop/'
Ref.DIR_DATA_DEM <- './Data/DEM'
Ref.DIR_DATA_SPI <- './Data/SPI'
Ref.DIR_Outputs <- './Outputs/'

Ref.DIR_FUNC_Ref <- 'Ref.R'
Ref.DIR_FUNC_MEF <- './Func/MEF.R'
Ref.DIR_FUNC_Lit <- './Func/Lit.R'
Ref.DIR_FUNC_Pop <- './Func/Pop.R'
Ref.DIR_FUNC_DEM <- './Func/DEM.R'
Ref.DIR_FUNC_SPI <- './Func/SPI.R'
Ref.DIR_FUNC_LitPop <- './Func/LitPop.R'
Ref.DIR_FUNC_Output <- './Func/Output.R'